### PR TITLE
Rename :db_migrations_location to :migrations_location

### PR DESCRIPTION
**Pull request by janko-m**
This makes the naming consistent with `:schema_location` and `:seeds_location` options.

What do you think?

### CODE REVIEW

**Comment by rosenfeld** [comment]
Yes, it makes sense. Thanks :)

**Comment by rosenfeld** [comment]
I'm just back to home. I intend to find some time before going to sleep to add yet another "irb" or "sequel_shell" action to open an irb session through the "sequel" command, similar to how the "shell" action opens a psql session for postgres databases. Any suggestions for how I should name such an action that will basically act as "bundle exec sequel uri"?

**Comment by rosenfeld** [comment]
After that I'll release a new version with your change plus the new supported action.

**Comment by rosenfeld** [comment]
Also, I'd love to hear suggestions on how to properly test such actions that replace the process with another one by callling `Kernel::exec`. The simplest would be to just mock `exec` and make sure it was called with the correct arguments, but that doesn't mean it really works as intended. Properly testing such features would probably mean spawning a new process, replacing stdin and making sure it works as intended, but I'm not really sure it worths the headache ;) Maybe I'll start by just mocking Kernel#exec and if I notice some regression that passed the mock test, I'd then reconsider a more robust approach to test such actions. Since those actions are not really that critical, I guess it makes sense to start by just mocking `exec`. Just let me know if you have any suggestions :)

**Comment by janko-m** [comment]
> Any suggestions for how I should name such an action that will basically act as "bundle exec sequel uri"?

Good idea, I think that `rake db:console` might be a good name, what do you think?

> Also, I'd love to hear suggestions on how to properly test such actions that replace the process with another one by callling `Kernel::exec`.

So, we essentially want to test that executing `rake db:shell` opens a `psql` console, right? For the sake of simplicity, I'll just open `psql` directly in my examples. At first I tried using `IO.popen`:

```rb
IO.popen("psql", "r+") do |io|
  io.puts("help")
  io.puts("\\q")
  expect(output.read).to include("You are using psql, the command-line interface to PostgreSQL.")
end
```

However, the problem is that the `psql` command actually won't open an interactive terminal if it detects that it's not being run from a TTY (terminal). As an example, `git diff` will pipe long diffs into `less`, but only if it's run from the terminal. This detection can be done in Ruby scripts as well:

```rb
if STDOUT.tty?
  # do something that would make sense in a Terminal
end
```

As you probably guessed, when a shell command is run with `IO.popen`, the script will detect it's not run from a terminal, as the following script proves:

```sh
$ ruby -e 'puts STDOUT.tty?'
true
$ ruby -e 'IO.popen(["ruby", "-e", "puts $stdout.tty?"]) { |io| puts io.read }'
false
```

After some searching, I found that the Ruby standard library comes with a `pty` standard library, which allows you to run shell commands inside a new allocated terminal. Using `pty` is actually a lot like using `IO.popen`:

```rb
require "pty"

PTY.spawn("psql") do |output, input, pid|
  input.puts("help")
  input.puts("\\q")
  expect(output.read).to include("You are using psql, the command-line interface to PostgreSQL.")
end
```

So that could be the basis of testing the `rake db:shell` tasks.

**Comment by rosenfeld** [comment]
Awesome, thanks, I'll give 'pty' a try on Monday, as tomorrow it's very likely I'll spend the entire day out of home.
I just released a new version a few hours ago using "irb" as the name, but I liked the "console" suggestion. I'll rename it and release a new version.

**Comment by rosenfeld** [comment]
Well, actually I think I'm already tired and it would be better to wait for some more discussion before this change. It's confusing to me to have both "shell" and "console" actions, as it's not clear what they do. Maybe we should call them "sql_console" and "irb_console" or something like that... Any ideas?

**Comment by janko-m** [comment]
@rosenfeld Yes, I was thinking the same thing, `irb` definitely removes any ambiguity. `sql_console` and `irb_console` also sound really nice. I can't really decide; on one hand I like that `shell` and `irb` are shorter and don't have underscores, but on the other hand both are "shell". But that's fine for me, as I still associate "shell" more with a direct console to the database.

**Comment by rosenfeld** [comment]
Ok, let's give it a bit more time then to see if someone else joins the discussion and we can get back to that subject later.

**Comment by rosenfeld** [comment]
Also, "irb_console" looks a bit weird, don't you think? After all, irb is supposed to be a console already anyway, so it sounds like repl_console when we already know that a repl is a console :) Maybe it would have to be called something like ruby_console instead, or sequel_console, hoping that Sequel users will understand the difference between sql_console and sequel_console :)

**Comment by rosenfeld** [comment]
Thank you for the suggestion of using PTY, @janko-m 
I was able to implement the missing tests, although I don't understand why this test isn't working on JRuby, even though the rake task itself works:

https://github.com/rosenfeld/sequel_tools/commit/7edad6ba44b066540349a4b2ab9e57834cf2bb19#diff-51a5de4ac9b469831db8c44631489c4cR6

Any ideas?

The curious thing is that the "shell" action test is about the same and works under JRuby.

**Comment by janko-m** [comment]
@rosenfeld No ideas unfortunately 🤷‍♂️

**Pull request merged**
