### PR TITLE
Update create_db.rb

### PR DESCRIPTION
**Pull request by AlexeyMatskevich**
Don't return exit code when database already exists

### CODE REVIEW

**Comment by rosenfeld** [comment]
Hi, sorry for the late reply. Those exit codes have been designed this way so that one could do something like `rake db:create && echo success`. When the database already exists, the db:create command will fail because it already exists, and then the shell script could do something else in that case. Why would you prefer it to exit with success instead in those cases?

**Comment by AlexeyMatskevich** [comment]
Probably it will not be very correct on my part, I thought that it should work this way due to the fact that this is the usual behavior of rake tasks in the rails. Thanks @rosenfeld !

**Comment by rosenfeld** [comment]
I see, but I don't really see why following ActiveRecord Migrations conventions would be useful to this project, since the tasks themselves do not follow the same API anyway. I think success makes more sense to return when the task was successful and in my mind ignoring the creation of a database when requested is a failure, even if the reason is because the database already exists. If you have any actual case where you think it would be more usefull to exit with 0 in those cases, please reopen the issue explaining how it would be an improvements. Thanks.

**Comment by AlexeyMatskevich** [comment]
My use case is running db:setup in a hook for git pull, I will use your proposed solution to my problem :+1:

**Pull request closed without merging**
